### ISSUE TITLE
Sidekiq errors

### ISSUE THREAD

**Issue by jnylen** [opbeat/opbeat-ruby#10]
Hi,
I get this:

`
2016-02-01T14:23:03.607Z 7211 TID-ovlsyrz9g ERROR: !!! ERROR HANDLER THREW AN ERROR !!!
2016-02-01T14:23:03.609Z 7211 TID-ovlsyrz9g ERROR: wrong number of arguments (2 for 1)
2016-02-01T14:23:03.610Z 7211 TID-ovlsyrz9g ERROR: /home/jnylen/.gem/ruby/2.2.4/bundler/gems/opbeat-ruby-7df5c6c1130e/lib/opbeat/integration/sidekiq.rb:33:in 'block (2 levels) in <top (required)>'
/home/jnylen/.gem/ruby/2.2.4/gems/sidekiq-4.0.2/lib/sidekiq/exception_handler.rb:20:in 'call'
/home/jnylen/.gem/ruby/2.2.4/gems/sidekiq-4.0.2/lib/sidekiq/exception_handler.rb:20:in 'block in handle_exception'
/home/jnylen/.gem/ruby/2.2.4/gems/sidekiq-4.0.2/lib/sidekiq/exception_handler.rb:18:in 'each'
/home/jnylen/.gem/ruby/2.2.4/gems/sidekiq-4.0.2/lib/sidekiq/exception_handler.rb:18:in 'handle_exception'
/home/jnylen/.gem/ruby/2.2.4/gems/sidekiq-4.0.2/lib/sidekiq/processor.rb:142:in 'rescue in process'
/home/jnylen/.gem/ruby/2.2.4/gems/sidekiq-4.0.2/lib/sidekiq/processor.rb:146:in 'process'
/home/jnylen/.gem/ruby/2.2.4/gems/sidekiq-4.0.2/lib/sidekiq/processor.rb:79:in 'process_one'
/home/jnylen/.gem/ruby/2.2.4/gems/sidekiq-4.0.2/lib/sidekiq/processor.rb:67:in 'run'
/home/jnylen/.gem/ruby/2.2.4/gems/sidekiq-4.0.2/lib/sidekiq/util.rb:16:in 'watchdog'
/home/jnylen/.gem/ruby/2.2.4/gems/sidekiq-4.0.2/lib/sidekiq/util.rb:24:in 'block in safe_thread'
`

When a ActiveRecord NotFound error occur.

**Comment by mikker** [comment]
Thank you for finding this @jnylen! It should be fixed in `master`.
