### ISSUE TITLE
Upgrading from v2

### ISSUE THREAD

**Issue by calvincorreli** [opbeat/opbeat-ruby#22]
Is there an upgrade guide from v2 of the gem?

I’m using

```ruby
Opbeat.set_context
```

which doesn’t exist anymore.

I tried adding the code from your docs:

```ruby
Rails.application.configure do |config|
  # ...
  config.opbeat.organization_id = 'XXX'
  config.opbeat.app_id = 'XXX'
  config.opbeat.secret_token = 'XXX'
end
```
but it fails:

```shell
➜  Simplero git:(master) ✗ rc
/Users/calvin/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/bundler/gems/rails-e90c76b83397/railties/lib/rails/railtie/configuration.rb:95:in `method_missing': undefined method `opbeat' for #<Rails::Application::Configuration:0x007ff65f451548> (NoMethodError)
	from /Users/calvin/Simplero/config/environments/development.rb:105:in `block in <top (required)>'
	from /Users/calvin/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/bundler/gems/rails-e90c76b83397/railties/lib/rails/railtie.rb:210:in `instance_eval'
	from /Users/calvin/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/bundler/gems/rails-e90c76b83397/railties/lib/rails/railtie.rb:210:in `configure'
	from /Users/calvin/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/bundler/gems/rails-e90c76b83397/railties/lib/rails/railtie.rb:182:in `configure'
```

I tried without the Rails.application.configure first, and it still fails:

```shell
➜  Simplero git:(master) ✗ rc
/Users/calvin/Simplero/config/initializers/opbeat.rb:6:in `block in <top (required)>': undefined method `opbeat' for #<Simplero::Application:0x007fe2cb2262e8> (NoMethodError)
	from /Users/calvin/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/bundler/gems/rails-e90c76b83397/railties/lib/rails/railtie.rb:210:in `instance_eval'
	from /Users/calvin/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/bundler/gems/rails-e90c76b83397/railties/lib/rails/railtie.rb:210:in `configure'
	from /Users/calvin/Simplero/config/initializers/opbeat.rb:5:in `<top (required)>'
	from /Users/calvin/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/bundler/gems/rails-e90c76b83397/activesupport/lib/active_support/dependencies.rb:268:in `load'
```

I tried in a config/initializers/opbeat.rb, and it still fails:

```shell
➜  Simplero git:(master) ✗ rc
/Users/calvin/Simplero/config/initializers/opbeat.rb:6:in `block in <top (required)>': undefined method `opbeat' for #<Opbeat::Configuration:0x007f89cf5b45b8> (NoMethodError)
	from /Users/calvin/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/opbeat-3.0.3/lib/opbeat/configuration.rb:62:in `initialize'
	from /Users/calvin/Simplero/config/initializers/opbeat.rb:5:in `new'
	from /Users/calvin/Simplero/config/initializers/opbeat.rb:5:in `<top (required)>'
	from /Users/calvin/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/bundler/gems/rails-e90c76b83397/activesupport/lib/active_support/dependencies.rb:268:in `load'
```

So far, it’s not easy at all, and I can’t find anything that says what I need to change.

Can you point me in the right direction?

**Comment by mikker** [comment]
Hi! You are right that the upgrade docs are pretty sparse. Move the setup code to `config/environments/production.rb` and you wont get the error that you've posted here. Using an initializer was the old way.

Also, you are correct that `set_context` hasn't been added since the rewrite. I'm sorry but I'm not sure if when or if it will be coming back.

Let me know if it still doesn't work for you :+1:

**Comment by calvincorreli** [comment]
I should be able to stick it in config/environments/development.rb as well, so I can test in development before I deploy to production, right? If you see my first stack trace above, that's what I did, and it didn't work.

If not set_context, how do I supply extra data like the current user, locale, time zone, etc.?

**Comment by mikker** [comment]
I usually put it in `config/application.rb` actually.
By default Opbeat doesn't run in dev mode but you can enable it with `config.opbeat.enabled_environments += ['development']`.

Opbeat should automatically add user information for most apps, see [this section in the README](https://github.com/opbeat/opbeat-ruby#user-information). For everything else there's [this](https://github.com/opbeat/opbeat-ruby/blob/master/lib/opbeat/error_message.rb#L68-L70) but there's no way to add it before the actual error occurs.

**Comment by mikker** [comment]
I suppose today is your lucky day: I just pushed version 3.0.4 to Rubygems with support for `Opbeat.set_context`. Thanks for using Opbeat :+1:

**Comment by calvincorreli** [comment]
Thank you, Mikkel. I’ll take another stab at upgrading.  

http://simplero.com
http://calvincorreli.com
