### ISSUE TITLE
[Opbeat] Invalid config - Skipping posting to Opbeat

### ISSUE THREAD

**Issue by BlackRabbitt** [opbeat/opbeat-ruby#25]
Opbeat throws an error `Configuration missing 'app_id'` and it skip posting to Opbeat. This error is only replicated in production whereas in development everything is fine. This means I've correct app_id.

My `opbeat.rb` looks like:
<img width="339" alt="screen shot 2016-03-31 at 5 01 01 pm" src="https://cloud.githubusercontent.com/assets/5746599/14174215/b16bbfa0-f762-11e5-9018-855a4e12b436.png">

> Error log Screenshot while routing error.

<img width="549" alt="screen shot 2016-03-31 at 4 57 51 pm" src="https://cloud.githubusercontent.com/assets/5746599/14174218/be213630-f762-11e5-8711-13fa2bc90508.png">

**Comment by mikker** [comment]
So just to be sure I understand you: You're sure that your app id is correctly set in production, and yet `opbeat-ruby` complains that it isn't?

**Comment by BlackRabbitt** [comment]
Exactly.

**Comment by mikker** [comment]
Is this still relevant? @BlackRabbitt

**Comment by BlackRabbitt** [comment]
And then I switched to Rollbar.

**Comment by mikker** [comment]
_Sick burn 😬_. Sorry to hear. If you ever want to try again I'm glad to help.
