### ISSUE TITLE
Upgrade question

### ISSUE THREAD

**Issue by mfkp** [opbeat/opbeat-ruby#30]
Working on upgrading an app from v2.0 to v3. One thing outstanding:

I have a few calls to `Opbeat.capture_exception` (and `capture_message`, but that's less important) scattered throughout my app. Is there any corollary to this in version 3?

Example:

```ruby
    begin
      abc
    rescue Exception => e
      Opbeat.capture_exception(e)
    end
```

**Comment by mikker** [comment]
Yes there is! It's been renamed to `report` (and `report_message`).
https://github.com/opbeat/opbeat-ruby/blob/master/lib/opbeat.rb#L108

And to make the confusion complete, `capture` now captures anything raised inside a block instead. Like

```ruby
Opbeat.capture do
  will_i_explode?
end
```

**Comment by mfkp** [comment]
Perfect, thanks for the help! 👍 💯
