### ISSUE TITLE
undefined method 'each' for ActionDispatch::Request

### ISSUE THREAD

**Issue by jeppeliisberg** [opbeat/opbeat-ruby#34]
After upgrading to rails 5 I see this in my logs:

```
** [Opbeat] Error capturing or sending exception undefined method `each' for #<ActionDispatch::Request:0x007fc96be63840>
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/opbeat-ruby-6b1705474436/lib/opbeat/error_message/http.rb:29:in `from_rack_env'
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/opbeat-ruby-6b1705474436/lib/opbeat/error_message.rb:64:in `from_exception'
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/opbeat-ruby-6b1705474436/lib/opbeat/client.rb:196:in `report'
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/opbeat-ruby-6b1705474436/lib/opbeat.rb:114:in `report'
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/opbeat-ruby-6b1705474436/lib/opbeat/integration/rails/inject_exceptions_catcher.rb:12:in `render_exception_with_opbeat'
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/debug_exceptions.rb:59:in `rescue in call'
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/debug_exceptions.rb:48:in `call'
```

Is the gem compatible with rails 5 or is it some other issue? I noticed that the builds haven't passed since 3.0.3 - I've reproduced this error with both 3.0.3, 3.0.7 and the fork with Rails 5 compatibility (https://github.com/opbeat/opbeat-ruby/pull/27)

Any ideas?

**Comment by jeppeliisberg** [comment]
Just confirmed that this problem does not exist in rails 4.2.6 with gem 3.0.2 but it does exist in rails 5 with gem 3.0.2 - so seems to be related to the rails 5 upgrade.

**Comment by jeppeliisberg** [comment]
looks like it might be because `ActionDispatch::Request` now inherits from `Object`, not `Rack::Request` anymore and thus does not respond to `each` anymore.

Having a hard time figuring out what to do from here.

@mikker maybe you can hint me what it takes to fix this?

**Comment by mikker** [comment]
I haven't had any time to look at Rails 5 yet and I won't have any before at least september I'm afraid. If you figure it out please let me know but until I get some dedicated time I won't be of much help.

**Comment by mikker** [comment]
Fixed in master - will release new version in a minute.

Thanks!

**Comment by jeppeliisberg** [comment]
@mikker Thank you so much! :-)
