### ISSUE TITLE
filter_parameters not working as it should

### ISSUE THREAD

**Issue by tanwcw** [opbeat/opbeat-ruby#39]
I’m using your Opbeat-Ruby gem for my application, but I realized that there are some parameters which I use in my application is sent over to Opbeat, even though I have set those parameters to be filtered in `filter_parameters`. Here’s a snippet of of my code:

```
Rails.application.configure do
 config.opbeat = {
   organization_id: ENV['OPBEAT_ORG_ID'] ,
   app_id: ENV['OPBEAT_APP_ID'] ,
   secret_token: ENV['OPBEAT_SECRET_TOKEN'],
   filter_parameters: [ :password, :password_confirmation, :current_password, :token, :secret, :_secret2 ]
}
```

`:_secret2` is still being logged inside Opbeat.

**Comment by tanwcw** [comment]
@mikker Any updates?

**Comment by mikker** [comment]
Sorry, no. I haven't much time to spare these days so it might take a week or so before I get a chance to take a look.
