### ISSUE TITLE
A before hook to filter exceptions

### ISSUE THREAD

**Issue by zedtux** [opbeat/opbeat-ruby#53]
As of now, the only way to filter exceptions is [the `excluded_exceptions` array](https://github.com/opbeat/opbeat-ruby/blob/dd48dfa480e451e090a4734ec897410b24b85b44/lib/opbeat/error_message.rb#L47).

I have the error with class `ActionController::RoutingError` which happens a lot, especially when some bots are scanning my app, and while I don't want to be spamed all the day long, I don't want to ignore ALL of the `ActionController::RoutingError` exceptions.

Having a before hook, juste before [the `excluded_exceptions` array](https://github.com/opbeat/opbeat-ruby/blob/dd48dfa480e451e090a4734ec897410b24b85b44/lib/opbeat/error_message.rb#L47), passing the exception as a parameter would allow us to check some details about the exception, like in my case the message content using a Regex, a filter the exception with a finer granularity.

Something like:

```ruby
config.opbeat.before_sending do |exception|
  if exception.message ~= /my message/
    return false # Prevent sending the exception
  end
end
```

**Comment by mikker** [comment]
Hi @zedtux! Opbeat is soon shutting down so I'm afraid there won't be put any more work into this project.

Good news is, we've moved to @elastic! Elastic APM is out and there's a [Ruby agent out in beta](https://github.com/elastic/apm-agent-ruby). Even more good news: It does almost all of what this does and more – including this exact feature you are requesting 😄 

Let me know if I can help with the transition.

**Comment by zedtux** [comment]
Thank you @mikker for your comment.

> Opbeat is soon shutting down

😨 Oh? Really? That's too bad 😞.

If I understand correctly, opbeat web platform will disappear and we have now to install the Elastic Stack in order to get the same thing?

**Comment by mikker** [comment]
That's correct. Soon enough Elastic APM will be available on Elastic Cloud so you won't necessarily have to set it all up yourself. But yes, right now, you need Elasticsearch, Kibana and an instance of `apm-server`.

**Comment by zedtux** [comment]
OK then thank you @mikker for your comments. Meanwhile I will keep an eye on Elastic APM in the Elastic Cloud, I will search for another solution similar to Opbeat.
